sudo: false
language: sourcepawn

addons:
  apt_packages:
    - lib32stdc++6

matrix:
  allow_failures:
    - env: SOURCEMOD=1.10

env:
  - SOURCEMOD=1.9
  - SOURCEMOD=1.10

before_script:
  - wget "https://www.sourcemod.net/latest.php?version=$SOURCEMOD&os=linux" -O sourcemod-$SOURCEMOD-linux.tar.gz
  - tar -xzf sourcemod-$SOURCEMOD-linux.tar.gz
  - cd addons/sourcemod/scripting/
  - chmod +x spcomp

script:
  - cd addons/sourcemod/scripting/
  - ./compile.sh swarm/*.sp
